spring.application.name=LolTracker

spring.data.mongodb.uri=${MONGODB_URI}

riot.api.key=${RIOT_API_KEY}
riot.api.region=europe
riot.api.platform=eun1
riot.api.ddragon-version=14.17.1

# Gdzie stoi Kafka
spring.kafka.bootstrap-servers=localhost:9092

# Konfiguracja konsumenta
spring.kafka.consumer.group-id=lol-analytics-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Konfiguracja producenta
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer